services:
  backend:
    ports:
      - "8050:8000"
    volumes:
      - ./backend/src/:/app/src/
    environment:
      - DJANGO_DEBUG=1

  frontend:
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src/:/app/src/
    environment:
      - VITE_API=http://localhost:8050
    command: bun run dev --host 0.0.0.0 --port 5173 --no-open

  db:
    ports:
      - "5439:5432"
