/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * API endpoint for viewing and managing Carts.
 * Accessible at /api/cart/
 */
export const CartListQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of results to return per page.'),
  "offset": zod.number().optional().describe('The initial index from which to return the results.'),
  "ordering": zod.string().optional().describe('Which field to use when ordering the results.'),
  "search": zod.string().optional().describe('A search term.')
})

export const CartListResponse = zod.object({
  "count": zod.number(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "studies": zod.array(zod.object({
  "id": zod.string(),
  "added": zod.iso.datetime({"offset":true})
}).describe('Serializer for CartItem model.'))
}).describe('Serializer for Cart model.'))
})


/**
 * Create a new cart with the given name.
 *
 * Expects a JSON body with the following structure:
 * {
 *     "studies": [
 *         {
 *         "id": "GSE35357",
 *         "added": "2025-12-12T11:21:35.895Z"
 *         },
 *         {
 *         "id": "GSE149008",
 *         "added": "2025-12-12T11:21:36.627Z"
 *         },
 *         {
 *         "id": "GSE45968",
 *         "added": "2025-12-12T11:21:37.293Z"
 *         }
 *     ],
 *     "name": "yowza"
 * }
 */
export const CartCreateBody = zod.object({
  "name": zod.string()
}).describe('Serializer for Cart model.')

export const CartCreateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "studies": zod.array(zod.object({
  "id": zod.string(),
  "added": zod.iso.datetime({"offset":true})
}).describe('Serializer for CartItem model.'))
}).describe('Serializer for Cart model.')


/**
 * API endpoint for viewing and managing Carts.
 * Accessible at /api/cart/
 */
export const CartRetrieveParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this cart.')
})

export const CartRetrieveResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "studies": zod.array(zod.object({
  "id": zod.string(),
  "added": zod.iso.datetime({"offset":true})
}).describe('Serializer for CartItem model.'))
}).describe('Serializer for Cart model.')


/**
 * API endpoint for viewing and managing Carts.
 * Accessible at /api/cart/
 */
export const CartUpdateParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this cart.')
})

export const CartUpdateBody = zod.object({
  "name": zod.string()
}).describe('Serializer for Cart model.')

export const CartUpdateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "studies": zod.array(zod.object({
  "id": zod.string(),
  "added": zod.iso.datetime({"offset":true})
}).describe('Serializer for CartItem model.'))
}).describe('Serializer for Cart model.')


/**
 * API endpoint for viewing and managing Carts.
 * Accessible at /api/cart/
 */
export const CartPartialUpdateParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this cart.')
})

export const CartPartialUpdateBody = zod.object({
  "name": zod.string().optional()
}).describe('Serializer for Cart model.')

export const CartPartialUpdateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "studies": zod.array(zod.object({
  "id": zod.string(),
  "added": zod.iso.datetime({"offset":true})
}).describe('Serializer for CartItem model.'))
}).describe('Serializer for Cart model.')


/**
 * API endpoint for viewing and managing Carts.
 * Accessible at /api/cart/
 */
export const CartDestroyParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this cart.')
})

export const CartDestroyResponse = zod.void()


/**
 * API endpoint for downloading cart contents.
 *
 * Expects a JSON body with the following structure:
 * {
 *     "ids": [
 *         "GSE35357",
 *         "GSE149008",
 *         "GSE45968"
 *     ]
 * }
 *
 * Query parameters:
 * - type (optional): 'json' or 'csv' (default: 'json')
 * - filename (optional): desired filename (default: 'cart_download')
 */
export const CartDownloadCreateBody = zod.object({
  "name": zod.string()
}).describe('Serializer for Cart model.')

export const CartDownloadCreateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "studies": zod.array(zod.object({
  "id": zod.string(),
  "added": zod.iso.datetime({"offset":true})
}).describe('Serializer for CartItem model.'))
}).describe('Serializer for Cart model.')


/**
 * API endpoint for searching ontology terms.
 * Accessible at /api/ontology-search/
 *
 * Query parameters:
 * - query (required): The search query string
 * - max_results (optional): Maximum number of results to return (default: 50)
 */
export const ontologySearchListQueryMaxResultsDefault = 50;

export const OntologySearchListQueryParams = zod.object({
  "max_results": zod.number().default(ontologySearchListQueryMaxResultsDefault).describe('Maximum number of results to return'),
  "query": zod.string().describe('Search query string')
})

export const OntologySearchListResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "series": zod.string(),
  "ontology": zod.string(),
  "type": zod.string(),
  "synonym": zod.string(),
  "scope": zod.string(),
  "sim": zod.number(),
  "scope_weight": zod.number(),
  "overall_rank": zod.number(),
  "is_exact": zod.boolean()
}).describe('Serializer for OntologySearchResults model.')
export const OntologySearchListResponse = zod.array(OntologySearchListResponseItem)


/**
 * ReadOnly API endpoint for viewing Organisms.
 * Accessible at /api/organisms/
 */
export const OrganismsListQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of results to return per page.'),
  "offset": zod.number().optional().describe('The initial index from which to return the results.'),
  "ordering": zod.string().optional().describe('Which field to use when ordering the results.'),
  "search": zod.string().optional().describe('A search term.')
})

export const OrganismsListResponse = zod.object({
  "count": zod.number(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string()
}).describe('Serializer for Organism model.'))
})


/**
 * ReadOnly API endpoint for viewing Organisms.
 * Accessible at /api/organisms/
 */
export const OrganismsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this organism.')
})

export const OrganismsRetrieveResponse = zod.object({
  "id": zod.number(),
  "name": zod.string()
}).describe('Serializer for Organism model.')


/**
 * ReadOnly API endpoint for viewing GEOPlatforms.
 * Accessible at /api/platforms/
 */
export const PlatformsListQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of results to return per page.'),
  "offset": zod.number().optional().describe('The initial index from which to return the results.'),
  "ordering": zod.string().optional().describe('Which field to use when ordering the results.'),
  "search": zod.string().optional().describe('A search term.')
})

export const platformsListResponseResultsItemDataRowCountMin = -2147483648;
export const platformsListResponseResultsItemDataRowCountMax = 2147483647;



export const PlatformsListResponse = zod.object({
  "count": zod.number(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "gpl": zod.string(),
  "title": zod.string().nullish(),
  "status": zod.string().nullish(),
  "submission_date": zod.string().nullish(),
  "last_update_date": zod.string().nullish(),
  "technology": zod.string().nullish(),
  "distribution": zod.string().nullish(),
  "organism": zod.string().nullish(),
  "manufacturer": zod.string().nullish(),
  "manufacture_protocol": zod.string().nullish(),
  "coating": zod.string().nullish(),
  "catalog_number": zod.string().nullish(),
  "support": zod.string().nullish(),
  "description": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "data_row_count": zod.number().min(platformsListResponseResultsItemDataRowCountMin).max(platformsListResponseResultsItemDataRowCountMax).nullish(),
  "supplementary_file": zod.string().nullish(),
  "bioc_package": zod.string().nullish()
}).describe('Serializer for GEOPlatform model.'))
})


/**
 * ReadOnly API endpoint for viewing GEOPlatforms.
 * Accessible at /api/platforms/
 */
export const PlatformsRetrieveParams = zod.object({
  "gpl": zod.string().describe('A unique value identifying this geo platform.')
})

export const platformsRetrieveResponseDataRowCountMin = -2147483648;
export const platformsRetrieveResponseDataRowCountMax = 2147483647;



export const PlatformsRetrieveResponse = zod.object({
  "gpl": zod.string(),
  "title": zod.string().nullish(),
  "status": zod.string().nullish(),
  "submission_date": zod.string().nullish(),
  "last_update_date": zod.string().nullish(),
  "technology": zod.string().nullish(),
  "distribution": zod.string().nullish(),
  "organism": zod.string().nullish(),
  "manufacturer": zod.string().nullish(),
  "manufacture_protocol": zod.string().nullish(),
  "coating": zod.string().nullish(),
  "catalog_number": zod.string().nullish(),
  "support": zod.string().nullish(),
  "description": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "data_row_count": zod.number().min(platformsRetrieveResponseDataRowCountMin).max(platformsRetrieveResponseDataRowCountMax).nullish(),
  "supplementary_file": zod.string().nullish(),
  "bioc_package": zod.string().nullish()
}).describe('Serializer for GEOPlatform model.')


/**
 * ReadOnly API endpoint for viewing GEOSamples.
 * Accessible at /api/samples/
 */
export const SamplesListQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of results to return per page.'),
  "offset": zod.number().optional().describe('The initial index from which to return the results.'),
  "ordering": zod.string().optional().describe('Which field to use when ordering the results.'),
  "search": zod.string().optional().describe('A search term.')
})

export const samplesListResponseResultsItemDataRowCountMin = -2147483648;
export const samplesListResponseResultsItemDataRowCountMax = 2147483647;

export const samplesListResponseResultsItemChannelCountMin = -2147483648;
export const samplesListResponseResultsItemChannelCountMax = 2147483647;



export const SamplesListResponse = zod.object({
  "count": zod.number(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "gsm": zod.string().describe('GEOSample ID'),
  "id": zod.string(),
  "title": zod.string().nullish(),
  "gpl_raw": zod.string().nullish().describe('GEOPlatform ID'),
  "status": zod.string().nullish(),
  "submission_date": zod.string().nullish(),
  "last_update_date": zod.string().nullish(),
  "type": zod.string().nullish(),
  "source_name_ch1": zod.string().nullish(),
  "organism_ch1": zod.string().nullish(),
  "characteristics_ch1": zod.string().nullish(),
  "molecule_ch1": zod.string().nullish(),
  "label_ch1": zod.string().nullish(),
  "treatment_protocol_ch1": zod.string().nullish(),
  "extract_protocol_ch1": zod.string().nullish(),
  "label_protocol_ch1": zod.string().nullish(),
  "source_name_ch2": zod.string().nullish(),
  "organism_ch2": zod.string().nullish(),
  "characteristics_ch2": zod.string().nullish(),
  "molecule_ch2": zod.string().nullish(),
  "label_ch2": zod.string().nullish(),
  "treatment_protocol_ch2": zod.string().nullish(),
  "extract_protocol_ch2": zod.string().nullish(),
  "label_protocol_ch2": zod.string().nullish(),
  "hyb_protocol": zod.string().nullish(),
  "description": zod.string().nullish(),
  "data_processing": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "data_row_count": zod.number().min(samplesListResponseResultsItemDataRowCountMin).max(samplesListResponseResultsItemDataRowCountMax).nullish(),
  "channel_count": zod.number().min(samplesListResponseResultsItemChannelCountMin).max(samplesListResponseResultsItemChannelCountMax).nullish(),
  "doc": zod.string().nullish(),
  "series": zod.string().nullish()
}).describe('Serializer for GEOSample model.'))
})


/**
 * ReadOnly API endpoint for viewing GEOSamples.
 * Accessible at /api/samples/
 */
export const SamplesRetrieveParams = zod.object({
  "gsm": zod.string()
})

export const samplesRetrieveResponseDataRowCountMin = -2147483648;
export const samplesRetrieveResponseDataRowCountMax = 2147483647;

export const samplesRetrieveResponseChannelCountMin = -2147483648;
export const samplesRetrieveResponseChannelCountMax = 2147483647;



export const SamplesRetrieveResponse = zod.object({
  "gsm": zod.string().describe('GEOSample ID'),
  "id": zod.string(),
  "title": zod.string().nullish(),
  "gpl_raw": zod.string().nullish().describe('GEOPlatform ID'),
  "status": zod.string().nullish(),
  "submission_date": zod.string().nullish(),
  "last_update_date": zod.string().nullish(),
  "type": zod.string().nullish(),
  "source_name_ch1": zod.string().nullish(),
  "organism_ch1": zod.string().nullish(),
  "characteristics_ch1": zod.string().nullish(),
  "molecule_ch1": zod.string().nullish(),
  "label_ch1": zod.string().nullish(),
  "treatment_protocol_ch1": zod.string().nullish(),
  "extract_protocol_ch1": zod.string().nullish(),
  "label_protocol_ch1": zod.string().nullish(),
  "source_name_ch2": zod.string().nullish(),
  "organism_ch2": zod.string().nullish(),
  "characteristics_ch2": zod.string().nullish(),
  "molecule_ch2": zod.string().nullish(),
  "label_ch2": zod.string().nullish(),
  "treatment_protocol_ch2": zod.string().nullish(),
  "extract_protocol_ch2": zod.string().nullish(),
  "label_protocol_ch2": zod.string().nullish(),
  "hyb_protocol": zod.string().nullish(),
  "description": zod.string().nullish(),
  "data_processing": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "data_row_count": zod.number().min(samplesRetrieveResponseDataRowCountMin).max(samplesRetrieveResponseDataRowCountMax).nullish(),
  "channel_count": zod.number().min(samplesRetrieveResponseChannelCountMin).max(samplesRetrieveResponseChannelCountMax).nullish(),
  "doc": zod.string().nullish(),
  "series": zod.string().nullish()
}).describe('Serializer for GEOSample model.')


/**
 * ReadOnly API endpoint for viewing SearchTerms.
 * Accessible at /api/search-terms/
 */
export const SearchTermsListQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of results to return per page.'),
  "offset": zod.number().optional().describe('The initial index from which to return the results.'),
  "ordering": zod.string().optional().describe('Which field to use when ordering the results.'),
  "search": zod.string().optional().describe('A search term.')
})

export const searchTermsListResponseResultsItemTermMax = 256;



export const SearchTermsListResponse = zod.object({
  "count": zod.number(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "term": zod.string().max(searchTermsListResponseResultsItemTermMax),
  "series_id": zod.string().nullable(),
  "prob": zod.number().nullish(),
  "log2_prob_prior": zod.number().nullish(),
  "related_words": zod.string().nullish()
}).describe('Serializer for SearchTerm model.'))
})


/**
 * ReadOnly API endpoint for viewing SearchTerms.
 * Accessible at /api/search-terms/
 */
export const SearchTermsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this search term.')
})

export const searchTermsRetrieveResponseTermMax = 256;



export const SearchTermsRetrieveResponse = zod.object({
  "id": zod.number(),
  "term": zod.string().max(searchTermsRetrieveResponseTermMax),
  "series_id": zod.string().nullable(),
  "prob": zod.number().nullish(),
  "log2_prob_prior": zod.number().nullish(),
  "related_words": zod.string().nullish()
}).describe('Serializer for SearchTerm model.')


/**
 * ReadOnly API endpoint for viewing GEOSeries.
 * Accessible at /api/series/
 */
export const StudyListQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of results to return per page.'),
  "offset": zod.number().optional().describe('The initial index from which to return the results.'),
  "ordering": zod.string().optional().describe('Which field to use when ordering the results.'),
  "search": zod.string().optional().describe('A search term.')
})

export const studyListResponseResultsItemPubmedIdMin = -9223372036854776000;
export const studyListResponseResultsItemPubmedIdMax = 9223372036854776000;



export const StudyListResponse = zod.object({
  "count": zod.number(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "name": zod.string(),
  "id": zod.string(),
  "status": zod.string().nullish(),
  "submitted_at": zod.iso.datetime({"offset":true}),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studyListResponseResultsItemPubmedIdMin).max(studyListResponseResultsItemPubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "confidence": zod.record(zod.string(), zod.unknown()).describe('Compute confidence level based on prob.'),
  "sample_count": zod.number().describe('Get the number of samples associated with this series.'),
  "database": zod.array(zod.string()),
  "platform": zod.string().describe('Get the platform name associated with this series.'),
  "keywords": zod.array(zod.string()).describe('Extract keywords from the series summary.'),
  "classification": zod.string().describe('Returns values Positive or Negative; supposed to represent \'Classification of study in model training\'?')
}).describe('Serializer for GEOSeries model.'))
})


/**
 * ReadOnly API endpoint for viewing GEOSeries.
 * Accessible at /api/series/
 */
export const StudyRetrieveParams = zod.object({
  "gse": zod.string().describe('A unique value identifying this geo series.')
})

export const studyRetrieveResponsePubmedIdMin = -9223372036854776000;
export const studyRetrieveResponsePubmedIdMax = 9223372036854776000;



export const StudyRetrieveResponse = zod.object({
  "name": zod.string(),
  "id": zod.string(),
  "status": zod.string().nullish(),
  "submitted_at": zod.iso.datetime({"offset":true}),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studyRetrieveResponsePubmedIdMin).max(studyRetrieveResponsePubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "confidence": zod.record(zod.string(), zod.unknown()).describe('Compute confidence level based on prob.'),
  "sample_count": zod.number().describe('Get the number of samples associated with this series.'),
  "database": zod.array(zod.string()),
  "platform": zod.string().describe('Get the platform name associated with this series.'),
  "keywords": zod.array(zod.string()).describe('Extract keywords from the series summary.'),
  "classification": zod.string().describe('Returns values Positive or Negative; supposed to represent \'Classification of study in model training\'?')
}).describe('Serializer for GEOSeries model.')


/**
 * ReadOnly API endpoint for viewing GEOSeries.
 * Accessible at /api/series/
 */
export const StudySamplesRetrieveParams = zod.object({
  "gse": zod.string().describe('A unique value identifying this geo series.')
})

export const studySamplesRetrieveResponsePubmedIdMin = -9223372036854776000;
export const studySamplesRetrieveResponsePubmedIdMax = 9223372036854776000;



export const StudySamplesRetrieveResponse = zod.object({
  "name": zod.string(),
  "id": zod.string(),
  "status": zod.string().nullish(),
  "submitted_at": zod.iso.datetime({"offset":true}),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studySamplesRetrieveResponsePubmedIdMin).max(studySamplesRetrieveResponsePubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "confidence": zod.record(zod.string(), zod.unknown()).describe('Compute confidence level based on prob.'),
  "sample_count": zod.number().describe('Get the number of samples associated with this series.'),
  "database": zod.array(zod.string()),
  "platform": zod.string().describe('Get the platform name associated with this series.'),
  "keywords": zod.array(zod.string()).describe('Extract keywords from the series summary.'),
  "classification": zod.string().describe('Returns values Positive or Negative; supposed to represent \'Classification of study in model training\'?')
}).describe('Serializer for GEOSeries model.')


/**
 * ReadOnly API endpoint for viewing GEOSeries.
 * Accessible at /api/series/
 */
export const studyFeedbackCreateBodyPubmedIdMin = -9223372036854776000;
export const studyFeedbackCreateBodyPubmedIdMax = 9223372036854776000;



export const StudyFeedbackCreateBody = zod.object({
  "status": zod.string().nullish(),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studyFeedbackCreateBodyPubmedIdMin).max(studyFeedbackCreateBodyPubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish()
}).describe('Serializer for GEOSeries model.')

export const studyFeedbackCreateResponsePubmedIdMin = -9223372036854776000;
export const studyFeedbackCreateResponsePubmedIdMax = 9223372036854776000;



export const StudyFeedbackCreateResponse = zod.object({
  "name": zod.string(),
  "id": zod.string(),
  "status": zod.string().nullish(),
  "submitted_at": zod.iso.datetime({"offset":true}),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studyFeedbackCreateResponsePubmedIdMin).max(studyFeedbackCreateResponsePubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "confidence": zod.record(zod.string(), zod.unknown()).describe('Compute confidence level based on prob.'),
  "sample_count": zod.number().describe('Get the number of samples associated with this series.'),
  "database": zod.array(zod.string()),
  "platform": zod.string().describe('Get the platform name associated with this series.'),
  "keywords": zod.array(zod.string()).describe('Extract keywords from the series summary.'),
  "classification": zod.string().describe('Returns values Positive or Negative; supposed to represent \'Classification of study in model training\'?')
}).describe('Serializer for GEOSeries model.')


/**
 * ReadOnly API endpoint for viewing GEOSeries.
 * Accessible at /api/series/
 */
export const studyLookupCreateBodyPubmedIdMin = -9223372036854776000;
export const studyLookupCreateBodyPubmedIdMax = 9223372036854776000;



export const StudyLookupCreateBody = zod.object({
  "status": zod.string().nullish(),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studyLookupCreateBodyPubmedIdMin).max(studyLookupCreateBodyPubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish()
}).describe('Serializer for GEOSeries model.')

export const studyLookupCreateResponsePubmedIdMin = -9223372036854776000;
export const studyLookupCreateResponsePubmedIdMax = 9223372036854776000;



export const StudyLookupCreateResponse = zod.object({
  "name": zod.string(),
  "id": zod.string(),
  "status": zod.string().nullish(),
  "submitted_at": zod.iso.datetime({"offset":true}),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studyLookupCreateResponsePubmedIdMin).max(studyLookupCreateResponsePubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "confidence": zod.record(zod.string(), zod.unknown()).describe('Compute confidence level based on prob.'),
  "sample_count": zod.number().describe('Get the number of samples associated with this series.'),
  "database": zod.array(zod.string()),
  "platform": zod.string().describe('Get the platform name associated with this series.'),
  "keywords": zod.array(zod.string()).describe('Extract keywords from the series summary.'),
  "classification": zod.string().describe('Returns values Positive or Negative; supposed to represent \'Classification of study in model training\'?')
}).describe('Serializer for GEOSeries model.')


/**
 * ReadOnly API endpoint for viewing GEOSeries.
 * Accessible at /api/series/
 */
export const studySearchRetrieveResponsePubmedIdMin = -9223372036854776000;
export const studySearchRetrieveResponsePubmedIdMax = 9223372036854776000;



export const StudySearchRetrieveResponse = zod.object({
  "name": zod.string(),
  "id": zod.string(),
  "status": zod.string().nullish(),
  "submitted_at": zod.iso.datetime({"offset":true}),
  "last_update_date": zod.string().nullish(),
  "pubmed_id": zod.number().min(studySearchRetrieveResponsePubmedIdMin).max(studySearchRetrieveResponsePubmedIdMax).nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string(),
  "type": zod.string().nullish(),
  "contributor": zod.string().nullish(),
  "web_link": zod.string().nullish(),
  "overall_design": zod.string().nullish(),
  "repeats": zod.string().nullish(),
  "repeats_sample_list": zod.string().nullish(),
  "variable": zod.string().nullish(),
  "variable_description": zod.string().nullish(),
  "contact": zod.string().nullish(),
  "supplementary_file": zod.string().nullish(),
  "confidence": zod.record(zod.string(), zod.unknown()).describe('Compute confidence level based on prob.'),
  "sample_count": zod.number().describe('Get the number of samples associated with this series.'),
  "database": zod.array(zod.string()),
  "platform": zod.string().describe('Get the platform name associated with this series.'),
  "keywords": zod.array(zod.string()).describe('Extract keywords from the series summary.'),
  "classification": zod.string().describe('Returns values Positive or Negative; supposed to represent \'Classification of study in model training\'?')
}).describe('Serializer for GEOSeries model.')


