# Generated by Django 5.2.6 on 2025-10-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_entity', models.CharField(max_length=64)),
                ('to_entity', models.CharField(max_length=64)),
                ('relation_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('doc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('doc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.ManyToManyField(related_name='series_relations', to='api.platform')),
                ('samples', models.ManyToManyField(related_name='series_relations', to='api.sample')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_relations', to='api.series')),
            ],
        ),
        migrations.CreateModel(
            name='OrganismForPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, null=True)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organism')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_pairings', to='api.platform')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_pairings', to='api.sample')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_pairings', to='api.series')),
            ],
            options={
                'indexes': [models.Index(fields=['series'], name='api_organis_series__5a81b4_idx'), models.Index(fields=['sample'], name='api_organis_sample__523b3b_idx'), models.Index(fields=['platform'], name='api_organis_platfor_b9f499_idx'), models.Index(fields=['series', 'sample', 'platform'], name='api_organis_series__cefed6_idx')],
                'unique_together': {('series', 'sample', 'platform')},
            },
        ),
    ]
