# Generated by Django 5.2.6 on 2025-10-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
