# Generated by Django 5.2.7 on 2025-10-24 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_organism_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalrelation',
            name='from_entity',
        ),
        migrations.RemoveField(
            model_name='externalrelation',
            name='to_entity',
        ),
        migrations.AddField(
            model_name='externalrelation',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_relations', to='api.series'),
        ),
        migrations.AddField(
            model_name='externalrelation',
            name='to_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_sample_relations', to='api.sample'),
        ),
        migrations.AddField(
            model_name='externalrelation',
            name='to_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_series_relations', to='api.sample'),
        ),
        migrations.AddField(
            model_name='externalrelation',
            name='to_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
