# Generated by Django 5.2.7 on 2025-11-13 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_externalrelation_from_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=256, unique=True)),
                ('prob', models.FloatField()),
                ('log2_prob_prior', models.FloatField()),
                ('related_words', models.TextField(blank=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_terms', to='api.sample')),
            ],
        ),
    ]
