# Generated by Django 5.2.7 on 2025-11-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_searchterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='related_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
