# Generated by Django 5.2.7 on 2025-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_searchterm_related_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='sample',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
