# Generated by Django 5.2.7 on 2025-11-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_searchterm_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchterm',
            old_name='sample',
            new_name='sample_id',
        ),
    ]
