# Generated by Django 5.2.7 on 2025-11-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_sample_searchterm_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='term',
            field=models.CharField(max_length=256),
        ),
    ]
