# Generated by Django 5.2.7 on 2025-11-14 16:48

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_searchterm_term'),
    ]

    operations = [
        TrigramExtension(),
    ]
