# Generated by Django 5.2.7 on 2025-11-14 16:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20251114_1648'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchterm',
            index=django.contrib.postgres.indexes.GinIndex(fields=['related_words'], name='term_related_words_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
