# Generated by Django 5.2.7 on 2025-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_searchterm_term_related_words_trgm_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologySearchDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=256)),
                ('ontology', models.CharField(max_length=128)),
                ('type', models.CharField(db_column='type', max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('syn_exact', models.JSONField(blank=True, null=True)),
                ('syn_narrow', models.JSONField(blank=True, null=True)),
                ('syn_broad', models.JSONField(blank=True, null=True)),
                ('syn_related', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['term_id'], name='api_ontolog_term_id_3e9ab8_idx'), models.Index(fields=['ontology'], name='api_ontolog_ontolog_fb932c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OntologySynonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=256)),
                ('synonym', models.CharField(max_length=512)),
                ('scope', models.CharField(db_column='scope', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['term_id'], name='api_ontolog_term_id_020c56_idx'), models.Index(fields=['synonym'], name='api_ontolog_synonym_85f9b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='OntologyTerms',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('ontology', models.CharField(max_length=128)),
                ('type', models.CharField(db_column='type', max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['ontology'], name='api_ontolog_ontolog_a1ac3a_idx'), models.Index(fields=['type'], name='api_ontolog_type_683fd8_idx')],
            },
        ),
    ]
