# Generated by Django 5.2.7 on 2025-12-02 18:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_search_onto_func'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologySearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField()),
                ('name', models.CharField()),
                ('ontology', models.CharField()),
                ('type', models.CharField()),
                ('synonym', models.CharField()),
                ('scope', models.CharField()),
                ('sim', models.FloatField()),
                ('scope_weight', models.FloatField()),
                ('overall_rank', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddIndex(
            model_name='ontologysynonyms',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('synonym', config='simple'), name='api_ontosyn_syn_tsv_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologysynonyms',
            index=django.contrib.postgres.indexes.GinIndex(fields=['synonym'], name='api_ontosyn_syn_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='ontologyterms',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', config='simple'), name='api_ontoterms_name_tsv_idx'),
        ),
        migrations.AddIndex(
            model_name='ontologyterms',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='api_ontoterms_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
