# Generated by Django 5.2.7 on 2025-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ontologysearchresults_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['term'], name='api_searcht_term_0195b4_idx'),
        ),
    ]
