# Generated by Django 5.2.7 on 2025-12-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_searchterm_api_searcht_term_0195b4_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ontologyterms',
            index=models.Index(fields=['id'], name='api_ontolog_id_69f9a8_idx'),
        ),
    ]
