# Generated by Django 5.2.7 on 2025-12-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ontologyterms_api_ontolog_id_69f9a8_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchterm',
            old_name='sample_id',
            new_name='series_id',
        ),
    ]
