# Generated by Django 5.2.7 on 2025-12-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_sample_id_searchterm_series_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchterm',
            name='series_id',
        ),
        migrations.AddField(
            model_name='searchterm',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_terms', to='api.series'),
        ),
    ]
