# Generated by Django 5.2.7 on 2025-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_searchterm_series_id_searchterm_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEOSeriesMetadata',
            fields=[
                ('title', models.TextField(blank=True, null=True)),
                ('gse', models.CharField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, null=True)),
                ('submission_date', models.CharField(blank=True, null=True)),
                ('last_update_date', models.CharField(blank=True, null=True)),
                ('pubmed_id', models.BigIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('contributor', models.TextField(blank=True, null=True)),
                ('web_link', models.TextField(blank=True, null=True)),
                ('overall_design', models.TextField(blank=True, null=True)),
                ('repeats', models.TextField(blank=True, null=True)),
                ('repeats_sample_list', models.TextField(blank=True, null=True)),
                ('variable', models.TextField(blank=True, null=True)),
                ('variable_description', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('supplementary_file', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
