# Generated by Django 5.2.7 on 2025-12-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_geoseriesmetadata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geoseriesmetadata',
            index=models.Index(fields=['gse'], name='api_geoseri_gse_297173_idx'),
        ),
    ]
