# Generated by Django 5.2.7 on 2025-12-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_geoseriesmetadata_api_geoseri_gse_297173_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField()),
                ('url', models.CharField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='api.series')),
            ],
            options={
                'indexes': [models.Index(fields=['series'], name='api_seriesd_series__fff5b0_idx'), models.Index(fields=['database_name'], name='api_seriesd_databas_02f924_idx')],
                'unique_together': {('series', 'database_name')},
            },
        ),
    ]
