# Generated by Django 5.2.7 on 2025-12-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_seriesdatabase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriesdatabase',
            unique_together=set(),
        ),
    ]
