# Generated by Django 5.2.7 on 2026-01-28 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEOPlatformMetadata',
            fields=[
                ('gpl', models.CharField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('submission_date', models.TextField(blank=True, null=True)),
                ('last_update_date', models.TextField(blank=True, null=True)),
                ('technology', models.TextField(blank=True, null=True)),
                ('distribution', models.TextField(blank=True, null=True)),
                ('organism', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('manufacture_protocol', models.TextField(blank=True, null=True)),
                ('coating', models.TextField(blank=True, null=True)),
                ('catalog_number', models.TextField(blank=True, null=True)),
                ('support', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('web_link', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('data_row_count', models.IntegerField(blank=True, null=True)),
                ('supplementary_file', models.TextField(blank=True, null=True)),
                ('bioc_package', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['gpl'], name='api_geoplat_gpl_9f2a0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GEOSampleMetadata',
            fields=[
                ('gsm', models.CharField(help_text='Sample ID', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('gpl_raw', models.TextField(blank=True, db_column='gpl', help_text='Platform ID', null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('submission_date', models.TextField(blank=True, null=True)),
                ('last_update_date', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('source_name_ch1', models.TextField(blank=True, null=True)),
                ('organism_ch1', models.TextField(blank=True, null=True)),
                ('characteristics_ch1', models.TextField(blank=True, null=True)),
                ('molecule_ch1', models.TextField(blank=True, null=True)),
                ('label_ch1', models.TextField(blank=True, null=True)),
                ('treatment_protocol_ch1', models.TextField(blank=True, null=True)),
                ('extract_protocol_ch1', models.TextField(blank=True, null=True)),
                ('label_protocol_ch1', models.TextField(blank=True, null=True)),
                ('source_name_ch2', models.TextField(blank=True, null=True)),
                ('organism_ch2', models.TextField(blank=True, null=True)),
                ('characteristics_ch2', models.TextField(blank=True, null=True)),
                ('molecule_ch2', models.TextField(blank=True, null=True)),
                ('label_ch2', models.TextField(blank=True, null=True)),
                ('treatment_protocol_ch2', models.TextField(blank=True, null=True)),
                ('extract_protocol_ch2', models.TextField(blank=True, null=True)),
                ('label_protocol_ch2', models.TextField(blank=True, null=True)),
                ('hyb_protocol', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_processing', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('supplementary_file', models.TextField(blank=True, null=True)),
                ('data_row_count', models.IntegerField(blank=True, null=True)),
                ('channel_count', models.IntegerField(blank=True, null=True)),
                # ('platform', models.ForeignKey(blank=True, db_column='gpl_platform', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='api.geoplatformmetadata')),
                ('series', models.ForeignKey(blank=True, db_column='series_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='api.geoseriesmetadata')),
            ],
            options={
                'indexes': [models.Index(fields=['gsm'], name='api_geosamp_gsm_2a3d7a_idx'), models.Index(fields=['gpl_raw'], name='api_geosamp_gpl_ce7dc2_idx')],
            },
        ),
    ]
