# Generated by Django 5.2.7 on 2026-01-30 16:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_geoplatformmetadata_geosamplemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEOSeriesToPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gse', models.CharField(unique=True)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
            ],
        ),
        migrations.AddIndex(
            model_name='geosamplemetadata',
            index=models.Index(fields=['series'], name='api_geosamp_series__4df13a_idx'),
        ),
        migrations.AddIndex(
            model_name='geoseriestoplatforms',
            index=models.Index(fields=['gse'], name='api_geoseri_gse_1b5e43_idx'),
        ),
    ]
