# Generated by Django 5.2.7 on 2026-02-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_geoseriestoplatforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geosamplemetadata',
            name='doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geoseriesmetadata',
            name='doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='doc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
