# Generated by Django 5.2.7 on 2026-02-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_geosamplemetadata_doc_geoseriesmetadata_doc_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
        -- copy doc from Series to GEOSeriesMetadata
        UPDATE api_geoseriesmetadata g
        SET doc = s.doc
        FROM api_series s
        WHERE g.gse = s.series_id;
                          
        -- copy doc from Sample to GEOSampleMetadata
        UPDATE api_geosamplemetadata g
        SET doc = s.doc
        FROM api_sample s
        WHERE g.gsm = s.sample_id;
        """)
    ]
