# Generated by Django 5.2.7 on 2026-02-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_migrate_core_cols'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GEOSampleMetadata',
            new_name='GEOSample',
        ),
        migrations.RenameModel(
            old_name='GEOPlatformMetadata',
            new_name='GEOPlatform',
        ),
        migrations.RenameModel(
            old_name='GEOSeriesMetadata',
            new_name='GEOSeries',
        ),
        migrations.RenameModel(
            old_name='SeriesDatabase',
            new_name='GEOSeriesDatabase',
        ),
        migrations.RenameModel(
            old_name='SeriesRelations',
            new_name='GEOSeriesRelations',
        ),
        migrations.RenameModel(
            old_name='GEOSeriesToPlatforms',
            new_name='GEOSeriesToGEOPlatforms',
        ),
        migrations.RemoveField(
            model_name='externalrelation',
            name='series',
        ),
        migrations.RemoveField(
            model_name='externalrelation',
            name='to_sample',
        ),
        migrations.RemoveField(
            model_name='externalrelation',
            name='to_series',
        ),
        migrations.RemoveField(
            model_name='geosample',
            name='series',
        ),
        migrations.AlterUniqueTogether(
            name='organismforpairing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organismforpairing',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='organismforpairing',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='organismforpairing',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='organismforpairing',
            name='series',
        ),
        migrations.RemoveField(
            model_name='geoseriesrelations',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='geoseriesrelations',
            name='samples',
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='search_terms', to='api.geoseries'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geoseries'),
        ),
        migrations.RemoveField(
            model_name='geoseriesrelations',
            name='series',
        ),
        migrations.RemoveField(
            model_name='geoseriesdatabase',
            name='series',
        ),
        migrations.RenameIndex(
            model_name='geoplatform',
            new_name='api_geoplat_gpl_252b38_idx',
            old_name='api_geoplat_gpl_9f2a0a_idx',
        ),
        migrations.RenameIndex(
            model_name='geoseries',
            new_name='api_geoseri_gse_01d11b_idx',
            old_name='api_geoseri_gse_297173_idx',
        ),
        migrations.RenameIndex(
            model_name='geoseriestogeoplatforms',
            new_name='api_geoseri_gse_bd7e57_idx',
            old_name='api_geoseri_gse_1b5e43_idx',
        ),
        migrations.AddField(
            model_name='geosample',
            name='series',
            field=models.ForeignKey(blank=True, db_column='series_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='api.geoseries'),
        ),
        migrations.AddField(
            model_name='geoseriesdatabase',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='databases', to='api.geoseries'),
        ),
        migrations.AddField(
            model_name='geoseriesrelations',
            name='platforms',
            field=models.ManyToManyField(related_name='series_relations', to='api.geoplatform'),
        ),
        migrations.AddField(
            model_name='geoseriesrelations',
            name='samples',
            field=models.ManyToManyField(related_name='series_relations', to='api.geosample'),
        ),
        migrations.AddField(
            model_name='geoseriesrelations',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_relations', to='api.geoseries'),
        ),
        migrations.DeleteModel(
            name='ExternalRelation',
        ),
        migrations.DeleteModel(
            name='OrganismForPairing',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddIndex(
            model_name='geosample',
            index=models.Index(fields=['gsm'], name='api_geosamp_gsm_4d7ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='geosample',
            index=models.Index(fields=['series'], name='api_geosamp_series__5e8a72_idx'),
        ),
        migrations.AddIndex(
            model_name='geosample',
            index=models.Index(fields=['gpl_raw'], name='api_geosamp_gpl_597e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='geoseriesdatabase',
            index=models.Index(fields=['series'], name='api_geoseri_series__909d82_idx'),
        ),
        migrations.AddIndex(
            model_name='geoseriesdatabase',
            index=models.Index(fields=['database_name'], name='api_geoseri_databas_9f2673_idx'),
        ),
    ]
