# Generated by Django 5.2.7 on 2026-02-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_geosample_geoseriesdatabase_geoseriesrelations_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='geosample',
            name='api_geosamp_gsm_2a3d7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='geosample',
            name='api_geosamp_gpl_ce7dc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='geosample',
            name='api_geosamp_series__4df13a_idx',
        ),
        migrations.RemoveIndex(
            model_name='geoseriesdatabase',
            name='api_seriesd_series__fff5b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='geoseriesdatabase',
            name='api_seriesd_databas_02f924_idx',
        ),
        migrations.AlterField(
            model_name='geosample',
            name='gpl_raw',
            field=models.TextField(blank=True, db_column='gpl', help_text='GEOPlatform ID', null=True),
        ),
        migrations.AlterField(
            model_name='geosample',
            name='gsm',
            field=models.CharField(help_text='GEOSample ID', primary_key=True, serialize=False),
        ),
    ]
