# Generated by Django 5.2.7 on 2026-03-27 03:50

from django.db import migrations
from django.db.migrations import RunSQL

FUNC_DEFN = """
DROP FUNCTION IF EXISTS search_onto(text, integer);

CREATE FUNCTION search_onto(
    query text,
    max_results integer DEFAULT 50
)
RETURNS TABLE (
    id varchar, name varchar, ontology varchar, type varchar,
    synonym varchar, scope varchar,
    sim real, scope_weight real, overall_rank real, is_exact boolean
)
AS $$
    SELECT
        q.id,
        q.name,
        q.ontology,
        q.type,
        q.synonym,
        q.scope,
        q.sim,
        q.scope_weight,
        q.overall_rank,
        q.is_exact
    FROM (
        SELECT
            t.id,
            t.name,
            t.ontology,
            t.type,
            s.synonym,
            s.scope,
            calc.sim,
            calc.scope_weight,
            calc.sim * calc.scope_weight AS overall_rank,
            COALESCE(t.name = query OR s.synonym = query, FALSE) AS is_exact
        FROM api_ontologyterms t
        LEFT JOIN api_ontologysynonyms s
          ON s.term_id = t.id
        CROSS JOIN LATERAL (
            SELECT
                similarity(COALESCE(s.synonym, t.name, t.id, s.term_id), query) AS sim,
                CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END AS scope_weight
        ) calc
    ) q
    WHERE
        q.is_exact
        OR q.sim > 0.2
    ORDER BY
        q.is_exact DESC,
        q.overall_rank DESC
    LIMIT max_results;
$$ LANGUAGE sql;

alter function search_onto(text, integer) owner to meta2onto;
"""

# originally defined in 0012_search_onto_func.py, but updated here to be more efficient
OLD_FUNC_DEFN = """
-- drop the func first so we don't get errors if we change the args or return type
DROP FUNCTION IF EXISTS search_onto(text, integer);
-- simple fuzzy query, w/exact term matching prioritized
CREATE FUNCTION search_onto(
    query text,
    max_results integer DEFAULT 50
)
RETURNS TABLE (
    id varchar, name varchar, ontology varchar, type varchar,
    synonym varchar, scope varchar,
    sim real, scope_weight real, overall_rank real, is_exact boolean
)
AS $$
    SELECT
        t.id,
        t.name,
        t.ontology,
        t.type,
        s.synonym,
        s.scope,

        -- similarity score
        similarity(COALESCE(s.synonym, t.name, t.id), query) AS sim,

        -- scope weight
        CASE s.scope
            WHEN 'EXACT'   THEN 1.5
            WHEN 'NARROW'  THEN 1.3
            WHEN 'BROAD'   THEN 1.1
            WHEN 'RELATED' THEN 0.9
            ELSE 1.0
        END AS scope_weight,

        -- overall rank
        similarity(COALESCE(s.synonym, t.name, t.id, s.term_id), query) *
        CASE s.scope
            WHEN 'EXACT'   THEN 1.5
            WHEN 'NARROW'  THEN 1.3
            WHEN 'BROAD'   THEN 1.1
            WHEN 'RELATED' THEN 0.9
            ELSE 1.0
        END AS overall_rank,

        -- NEW: exact match flag
        CASE
            WHEN t.id = query OR s.term_id = query THEN TRUE
            ELSE FALSE
        END AS is_exact

    FROM api_ontologyterms t
    LEFT JOIN api_ontologysynonyms s
    ON s.term_id = t.id

    WHERE
        t.id = query
        OR s.term_id = query
        OR similarity(COALESCE(s.synonym, t.name, t.id, s.term_id), query) > 0.2

    -- NEW: exact matches sort first
    ORDER BY is_exact DESC, overall_rank DESC

    LIMIT max_results;
$$ LANGUAGE sql;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_feedback'),
    ]

    operations = [
        RunSQL(
            FUNC_DEFN,
            reverse_sql=OLD_FUNC_DEFN
        ),
    ]
