# Generated by Django 5.2.7 on 2026-03-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_optimize_search_onto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchterm',
            old_name='prob',
            new_name='confidence',
        ),
        migrations.RemoveField(
            model_name='searchterm',
            name='log2_prob_prior',
        ),
    ]
