# Generated by Django 5.2.7 on 2026-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_optimize_search_onto_v2'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['term', 'series'], name='searchterm_term_series_idx'),
        ),
    ]
