# Generated by Django 5.2.7 on 2026-06-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_searchterm_searchterm_term_series_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyTermRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=256)),
                ('performance', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
    ]
