# Generated by Django 5.2.7 on 2026-06-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_dedupe_search_onto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDbRefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField()),
                ('external_id', models.CharField(blank=True, help_text='ID of the series in the external database, if available', null=True)),
                ('series', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='external_db_refs', to='api.geoseries')),
            ],
            options={
                'indexes': [models.Index(fields=['series'], name='api_externa_series__994a4d_idx'), models.Index(fields=['database'], name='api_externa_databas_81871d_idx')],
                'unique_together': {('series', 'database')},
            },
        ),
    ]
