# Generated by Django 5.2.7 on 2026-06-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_facet_facetentry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='geoseriesdatabase',
            name='api_geoseri_databas_9f2673_idx',
        ),
        migrations.RenameField(
            model_name='geoseriesdatabase',
            old_name='database_name',
            new_name='database',
        ),
        migrations.AddIndex(
            model_name='geoseriesdatabase',
            index=models.Index(fields=['database'], name='api_geoseri_databas_b1f8de_idx'),
        ),
    ]
