# Generated by Django 5.2.7 on 2026-06-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_geoseriesdatabase_api_geoseri_databas_9f2673_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='externaldbrefs',
            index=models.Index(fields=['database', 'series_id'], name='api_externa_databas_e626f4_idx'),
        ),
        migrations.AddIndex(
            model_name='geoseriesdatabase',
            index=models.Index(fields=['database', 'series_id'], name='api_geoseri_databas_49f223_idx'),
        ),
    ]
