# Generated by Django 5.2.7 on 2026-06-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_externaldbrefs_api_externa_databas_e626f4_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('series_id', 'user_id')},
        ),
    ]
