# Generated by Django 5.2.7 on 2026-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geosample',
            index=models.Index(fields=['organism_ch1'], name='api_geosamp_organis_8c91f4_idx'),
        ),
    ]
