# Generated by Django 5.2.7 on 2026-06-24 23:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_geosample_api_geosamp_organis_8c91f4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='geosample',
            name='series_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, help_text='List of GSE IDs this sample belongs to', null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='geosample',
            index=models.Index(fields=['series_set'], name='api_geosamp_series__c62dec_idx'),
        ),
    ]
