# Generated by Django 5.2.7 on 2026-06-24 23:40

from django.db import migrations

from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_geosample_series_set_and_more'),
    ]

    operations = [
        RunSQL(
            """
            UPDATE api_geosample SET series_set = array_remove(regexp_split_to_array(trim(series_id), '\s*;\s*'), '')
            WHERE series_id IS NOT NULL;
            """,
            reverse_sql="""
            UPDATE api_geosample SET series_set = NULL;
            """
        ),
    ]
