# Generated by Django 5.2.7 on 2026-06-27 02:14

from django.db import migrations
from django.db.migrations import RunSQL

# when null is passed for max_results, the function will return all results (no limit)

FUNC_DEFN = """
DROP FUNCTION IF EXISTS search_onto(text, integer);

CREATE FUNCTION search_onto(
    query text,
    max_results integer DEFAULT 50
)
RETURNS TABLE (
    id varchar, name varchar, ontology varchar, type varchar,
    synonym varchar, scope varchar,
    sim real, scope_weight real, overall_rank real, is_exact boolean
)
SET pg_trgm.similarity_threshold = 0.2
AS $$
    SELECT
        d.id, d.name, d.ontology, d.type,
        d.synonym, d.scope,
        d.sim, d.scope_weight, d.overall_rank, d.is_exact
    FROM (
        SELECT DISTINCT ON (q.id)
            q.id, q.name, q.ontology, q.type,
            q.synonym, q.scope,
            q.sim, q.scope_weight, q.overall_rank, q.is_exact
        FROM (
            -- Branch 1: exact match on term id or name.
            -- No similarity calculation; wins all ranking.
            SELECT
                t.id, t.name, t.ontology, t.type,
                NULL::varchar AS synonym,
                NULL::varchar AS scope,
                1.0::real     AS sim,
                1.0::real     AS scope_weight,
                1.0::real     AS overall_rank,
                TRUE          AS is_exact
            FROM api_ontologyterms t
            WHERE (t.id = query OR t.name = query)
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )

            UNION ALL

            -- Branch 2: exact match on a synonym.
            -- Carries scope weight but no similarity cost.
            SELECT
                t.id, t.name, t.ontology, t.type,
                s.synonym,
                s.scope,
                1.0::real AS sim,
                CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END::real AS scope_weight,
                CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END::real AS overall_rank,
                TRUE AS is_exact
            FROM api_ontologyterms t
            JOIN api_ontologysynonyms s ON s.term_id = t.id
            WHERE s.synonym = query
              AND t.id    <> query
              AND t.name  <> query
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )

            UNION ALL

            -- Branch 3: fuzzy name match.
            -- Uses the trigram GIN index on api_ontologyterms.name via the %
            -- operator (controlled by the pg_trgm.similarity_threshold = 0.2 SET
            -- clause above, which replaces the previous > 0.2 threshold).
            SELECT
                t.id, t.name, t.ontology, t.type,
                NULL::varchar AS synonym,
                NULL::varchar AS scope,
                similarity(t.name, query)::real AS sim,
                1.0::real AS scope_weight,
                similarity(t.name, query)::real AS overall_rank,
                FALSE AS is_exact
            FROM api_ontologyterms t
            WHERE t.name % query
              AND t.name <> query
              AND t.id   <> query
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )

            UNION ALL

            -- Branch 4: fuzzy synonym match.
            -- Uses the trigram GIN index on api_ontologysynonyms.synonym via %.
            SELECT
                t.id, t.name, t.ontology, t.type,
                s.synonym,
                s.scope,
                similarity(s.synonym, query)::real AS sim,
                CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END::real AS scope_weight,
                (similarity(s.synonym, query) * CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END)::real AS overall_rank,
                FALSE AS is_exact
            FROM api_ontologyterms t
            JOIN api_ontologysynonyms s ON s.term_id = t.id
            WHERE s.synonym % query
              AND s.synonym <> query
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )
        ) q
        ORDER BY
            q.id,
            q.is_exact DESC,
            q.overall_rank DESC,
            q.scope_weight DESC,
            q.sim DESC,
            q.synonym NULLS LAST
    ) d
    ORDER BY
        d.is_exact DESC,
        d.overall_rank DESC,
        d.scope_weight DESC,
        d.sim DESC,
        d.id
    LIMIT CASE
        WHEN max_results IS NULL THEN NULL
        ELSE max_results
    END;
$$ LANGUAGE sql;

alter function search_onto(text, integer) owner to meta2onto;
"""

# reverse: the version from 0031_optimize_search_onto.py
OLD_FUNC_DEFN = """
DROP FUNCTION IF EXISTS search_onto(text, integer);

CREATE FUNCTION search_onto(
    query text,
    max_results integer DEFAULT 50
)
RETURNS TABLE (
    id varchar, name varchar, ontology varchar, type varchar,
    synonym varchar, scope varchar,
    sim real, scope_weight real, overall_rank real, is_exact boolean
)
SET pg_trgm.similarity_threshold = 0.2
AS $$
    SELECT
        d.id, d.name, d.ontology, d.type,
        d.synonym, d.scope,
        d.sim, d.scope_weight, d.overall_rank, d.is_exact
    FROM (
        SELECT DISTINCT ON (q.id)
            q.id, q.name, q.ontology, q.type,
            q.synonym, q.scope,
            q.sim, q.scope_weight, q.overall_rank, q.is_exact
        FROM (
            -- Branch 1: exact match on term id or name.
            -- No similarity calculation; wins all ranking.
            SELECT
                t.id, t.name, t.ontology, t.type,
                NULL::varchar AS synonym,
                NULL::varchar AS scope,
                1.0::real     AS sim,
                1.0::real     AS scope_weight,
                1.0::real     AS overall_rank,
                TRUE          AS is_exact
            FROM api_ontologyterms t
            WHERE (t.id = query OR t.name = query)
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )

            UNION ALL

            -- Branch 2: exact match on a synonym.
            -- Carries scope weight but no similarity cost.
            SELECT
                t.id, t.name, t.ontology, t.type,
                s.synonym,
                s.scope,
                1.0::real AS sim,
                CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END::real AS scope_weight,
                CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END::real AS overall_rank,
                TRUE AS is_exact
            FROM api_ontologyterms t
            JOIN api_ontologysynonyms s ON s.term_id = t.id
            WHERE s.synonym = query
              AND t.id    <> query
              AND t.name  <> query
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )

            UNION ALL

            -- Branch 3: fuzzy name match.
            -- Uses the trigram GIN index on api_ontologyterms.name via the %
            -- operator (controlled by the pg_trgm.similarity_threshold = 0.2 SET
            -- clause above, which replaces the previous > 0.2 threshold).
            SELECT
                t.id, t.name, t.ontology, t.type,
                NULL::varchar AS synonym,
                NULL::varchar AS scope,
                similarity(t.name, query)::real AS sim,
                1.0::real AS scope_weight,
                similarity(t.name, query)::real AS overall_rank,
                FALSE AS is_exact
            FROM api_ontologyterms t
            WHERE t.name % query
              AND t.name <> query
              AND t.id   <> query
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )

            UNION ALL

            -- Branch 4: fuzzy synonym match.
            -- Uses the trigram GIN index on api_ontologysynonyms.synonym via %.
            SELECT
                t.id, t.name, t.ontology, t.type,
                s.synonym,
                s.scope,
                similarity(s.synonym, query)::real AS sim,
                CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END::real AS scope_weight,
                (similarity(s.synonym, query) * CASE s.scope
                    WHEN 'EXACT'   THEN 1.5
                    WHEN 'NARROW'  THEN 1.3
                    WHEN 'BROAD'   THEN 1.1
                    WHEN 'RELATED' THEN 0.9
                    ELSE 1.0
                END)::real AS overall_rank,
                FALSE AS is_exact
            FROM api_ontologyterms t
            JOIN api_ontologysynonyms s ON s.term_id = t.id
            WHERE s.synonym % query
              AND s.synonym <> query
              AND EXISTS (
                  SELECT 1 FROM api_searchterm st WHERE st.term = t.id
              )
        ) q
        ORDER BY
            q.id,
            q.is_exact DESC,
            q.overall_rank DESC,
            q.scope_weight DESC,
            q.sim DESC,
            q.synonym NULLS LAST
    ) d
    ORDER BY
        d.is_exact DESC,
        d.overall_rank DESC,
        d.scope_weight DESC,
        d.sim DESC,
        d.id
    LIMIT max_results;
$$ LANGUAGE sql;

alter function search_onto(text, integer) owner to meta2onto;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_populate_series_set'),
    ]

    operations = [
        RunSQL(
            FUNC_DEFN,
            reverse_sql=OLD_FUNC_DEFN,
        ),
    ]
