# Generated by Django 5.2.7 on 2026-06-27 02:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('api', '0045_search_onto_nolimit'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY IF NOT EXISTS geosample_series_set_gin
                ON api_geosample
                USING GIN (series_set);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS geosample_series_set_gin;
            """,
        ),
    ]
