# Generated by Django 5.2.7 on 2026-07-01 14:12

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0046_add_geosample_series_set_gin'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY IF NOT EXISTS api_geoseri_submiss_a549eb_idx
                ON api_geoseries (submission_date);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS api_geoseri_submiss_a549eb_idx;
            """,
        ),
    ]
