# Generated by Django 5.2.7 on 2026-07-01 14:15

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_geoseries_submission_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoseries',
            name='samples_ct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE api_geoseries SET samples_ct = (SELECT COUNT(*) FROM api_geosample WHERE series_set @> ARRAY[api_geoseries.gse]::varchar[]);
            """
        ),
    ]
