# Generated by Django 5.2.7 on 2026-07-01 14:19

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('api', '0048_geoseries_samples_ct_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY IF NOT EXISTS api_geoseri_samples_ct_a549eb_idx
                ON api_geoseries (samples_ct);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS api_geoseri_samples_ct_a549eb_idx;
            """,
        ),
    ]
