# Generated by Django 5.2.7 on 2026-07-01 14:54

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_geosample_geosample_series_set_gin_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='geoseries',
            name='api_geoseri_gse_01d11b_idx',
        ),
        migrations.AlterField(
            model_name='geoseries',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
