# Generated by Django 5.2.7 on 2026-07-01 17:13

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_geoseries_submission_date_convert_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='geosample',
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=['series_set'],
                        name='geosample_series_set_gin',
                    ),
                ),
                migrations.AddIndex(
                    model_name='geoseries',
                    index=models.Index(
                        fields=['submission_date'],
                        name='api_geoseri_submiss_a549eb_idx',
                    ),
                ),
            ],
        ),
    ]
