# Generated by Django 5.2.7 on 2026-07-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_mark_series_set_submission_date_idxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositiveStudyAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=256)),
                ('series', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positive_annotations', to='api.geoseries')),
            ],
            options={
                'indexes': [models.Index(fields=['term', 'series'], name='api_positiv_term_e17b5e_idx')],
            },
        ),
    ]
