# Generated by Django 5.2.7 on 2026-07-02 20:37

from django.db import migrations, models

CREATE_MATERIALIZED_VIEW = """
CREATE MATERIALIZED VIEW api_geoseries_organism AS
WITH series_organisms AS (
    SELECT DISTINCT
        ag.gse AS series_id,
        btrim(o.organism_raw) AS organism
    FROM api_geosample AS gs
    CROSS JOIN LATERAL unnest(gs.series_set) AS g(gse_raw)
    JOIN api_geoseries AS ag
        ON ag.gse = btrim(g.gse_raw)
    CROSS JOIN LATERAL regexp_split_to_table(
        gs.organism_ch1,
        E'\\r?\\n'
    ) AS o(organism_raw)
    WHERE gs.organism_ch1 IS NOT NULL
      AND btrim(o.organism_raw) <> ''
)
SELECT
    row_number() OVER (
        ORDER BY series_id, organism
    )::bigint AS id,
    series_id,
    organism
FROM series_organisms;

REFRESH MATERIALIZED VIEW api_geoseries_organism;
"""

CREATE_UNIQUE_INDEX = """
CREATE UNIQUE INDEX api_geoseries_organism_gse_organism_uidx
    ON api_geoseries_organism (series_id, organism);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_positivestudyannotation'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_MATERIALIZED_VIEW,
            reverse_sql="DROP MATERIALIZED VIEW api_geoseries_organism;",
        ),
        migrations.RunSQL(
            sql=CREATE_UNIQUE_INDEX,
            reverse_sql=(
                "DROP INDEX api_geoseries_organism_gse_organism_uidx;"
            ),
        ),
        migrations.CreateModel(
            name='SearchSeriesOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField()),
            ],
            options={
                'db_table': 'api_geoseries_organism',
                'managed': False,
            },
        ),
    ]
