# Generated by Django 5.2.7 on 2026-07-02 23:59

from django.db import migrations, models


CREATE_MATERIALIZED_VIEW = """
CREATE MATERIALIZED VIEW api_geoseries_technology AS
WITH series_technologies AS (
    SELECT DISTINCT
        btrim(series_value.gse_raw) AS gse,
        btrim(platform.technology) AS technology
    FROM api_geosample AS sample
    CROSS JOIN LATERAL unnest(sample.series_set) AS series_value(gse_raw)
    JOIN api_geoseries AS series
        ON series.gse = btrim(series_value.gse_raw)
    JOIN api_geoplatform AS platform
        ON platform.gpl = sample.gpl
    WHERE series_value.gse_raw IS NOT NULL
      AND btrim(series_value.gse_raw) <> ''
      AND platform.technology IS NOT NULL
      AND btrim(platform.technology) <> ''
)
SELECT
    row_number() OVER (
        ORDER BY gse, technology
    )::bigint AS id,
    gse,
    technology
FROM series_technologies;

REFRESH MATERIALIZED VIEW api_geoseries_technology;
"""

CREATE_UNIQUE_INDEX = """
CREATE UNIQUE INDEX api_geoseries_technology_id_uidx
    ON api_geoseries_technology (id);

CREATE UNIQUE INDEX api_geoseries_technology_gse_technology_uidx
    ON api_geoseries_technology (gse, technology);
"""

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_searchseriesorganism'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_MATERIALIZED_VIEW,
            reverse_sql="DROP MATERIALIZED VIEW api_geoseries_technology;",
        ),
        migrations.RunSQL(
            sql=CREATE_UNIQUE_INDEX,
            reverse_sql=(
                "DROP INDEX api_geoseries_technology_gse_technology_uidx;"
            ),
        ),
        migrations.CreateModel(
            name='SearchSeriesTechnology',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('technology', models.CharField()),
            ],
            options={
                'db_table': 'api_geoseries_technology',
                'managed': False,
            },
        ),
    ]
