# Generated by Django 5.2.7 on 2026-07-07 18:08

from django.db import migrations, models

CREATE_MATERIALIZED_VIEW = """
CREATE MATERIALIZED VIEW api_geoseries_platform AS
WITH series_platforms AS (
    SELECT DISTINCT
        btrim(series_value.gse_raw) AS gse,
        btrim(platform.gpl) AS gpl
    FROM api_geosample AS sample
    CROSS JOIN LATERAL unnest(sample.series_set) AS series_value(gse_raw)
    JOIN api_geoseries AS series
        ON series.gse = btrim(series_value.gse_raw)
    JOIN api_geoplatform AS platform
        ON platform.gpl = sample.gpl
    WHERE series_value.gse_raw IS NOT NULL
      AND btrim(series_value.gse_raw) <> ''
      AND platform.gpl IS NOT NULL
      AND btrim(platform.gpl) <> ''
)
SELECT
    row_number() OVER (
        ORDER BY gse, gpl
    )::bigint AS id,
    gse,
    gpl AS platform
FROM series_platforms;

REFRESH MATERIALIZED VIEW api_geoseries_platform;
"""

CREATE_UNIQUE_INDEX = """
CREATE UNIQUE INDEX api_geoseries_platform_id_uidx
    ON api_geoseries_platform (id);

CREATE UNIQUE INDEX api_geoseries_platform_gse_gpl_uidx
    ON api_geoseries_platform (gse, platform);
"""

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_searchseriestechnology'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_MATERIALIZED_VIEW,
            reverse_sql="DROP MATERIALIZED VIEW api_geoseries_platform;",
        ),
        migrations.RunSQL(
            sql=CREATE_UNIQUE_INDEX,
            reverse_sql=(
                "DROP INDEX api_geoseries_platform_gse_gpl_uidx;"
            ),
        ),
        migrations.CreateModel(
            name='SearchSeriesPlatform',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('platform', models.CharField()),
            ],
            options={
                'db_table': 'api_geoseries_platform',
                'managed': False,
            },
        ),
    ]
