# Generated by Django 5.2.7 on 2026-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_sitestatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='search',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='term',
            field=models.CharField(blank=True, null=True),
        ),
    ]
